name: Release

on: 
  release:
    types:
      - published

jobs:
  release:
    name: Publish GitHub and Cocoapods release
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_12.app

      - name: Build
        run: |
          swift build -c release
          cp ./.build/x86_64-apple-macosx/release/figma-export ./Release/figma-export
          zip -r figma-export.zip Release LICENSE

      - name: "Get upload_url"
        run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"  
        id: release

      - name: Upload GitHub Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./figma-export.zip
          asset_name: figma-export.zip
          asset_content_type: application/zip

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          pod trunk push FigmaExport.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}